version: '3.8'
services:
  db:
    image: postgres:16
    container_name: teacher_student
    restart: always
    environment:
      POSTGRES_PASSWORD: 1313
      POSTGRES_USER: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 8765:5432
    expose:
      - 5432


    
