"""Change fk task param ondelete File

Revision ID: 27c5a849d0d9
Revises: 453f319cda70
Create Date: 2023-12-24 00:18:54.948652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c5a849d0d9'
down_revision = '453f319cda70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('file_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('file_task_id_fkey', 'task', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
