"""manual drop constraint for password

Revision ID: 435403bde678
Revises: f35647117c7b
Create Date: 2023-12-24 01:28:11.560704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435403bde678'
down_revision = 'f35647117c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)