"""add user to FileStorage

Revision ID: 453f319cda70
Revises: 81c6be1ff6e1
Create Date: 2023-12-22 06:03:04.243423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453f319cda70'
down_revision = '81c6be1ff6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(None, 'user_', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
