"""change column name filedata

Revision ID: 77f9b1ee5d3b
Revises: 435403bde678
Create Date: 2023-12-24 18:18:58.255032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77f9b1ee5d3b'
down_revision = '435403bde678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filedata', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('filedata')

    # ### end Alembic commands ###
