"""rop property status homework

Revision ID: 81c6be1ff6e1
Revises: bb2b0c69f0bb
Create Date: 2023-12-22 01:51:48.727190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c6be1ff6e1'
down_revision = 'bb2b0c69f0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
