"""many to many file task

Revision ID: b9dfb012c7ed
Revises: 77f9b1ee5d3b
Create Date: 2023-12-25 00:37:23.086325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dfb012c7ed'
down_revision = '77f9b1ee5d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_task',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'task_id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('file_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('file_task_id_fkey', 'task', ['task_id'], ['id'], ondelete='SET NULL')

    op.drop_table('file_task')
    # ### end Alembic commands ###
