"""change length email

Revision ID: d119454e1289
Revises: af79b8a5e774
Create Date: 2023-12-21 17:51:00.624643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd119454e1289'
down_revision = 'af79b8a5e774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=62),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=62),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)

    # ### end Alembic commands ###
